version: "3.8"

#!TODO change domain.hostname

services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: yourmailname
    hostname: mail.hostname.domain
    ports:
      - "25:25"
      - "587:587"
      - "465:465"
      - "993:993"
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
        #- ./docker-data/dms/config/dovecot/15-mailboxes.conf:/etc/dovecot/conf.d/15-mailboxes.conf:ro

      - /var/lib/acme/mail.hostname.domain/:/etc/letsencrypt/live/mail.hostname.domain/
      - /etc/localtime:/etc/localtime:ro

    environment:
      - ENABLE_FAIL2BAN=0
      - SSL_TYPE=letsencrypt
      - VIRTUAL_HOST=mail.hostname.domain
      - LETSENCRYPT_HOST=mail.hostname.domain
      - PERMIT_DOCKER=network
      - ONE_DIR=1
      - ENABLE_POSTGREY=1
      - ENABLE_CLAMAV=1
      - ENABLE_SPAMASSASSIN=0
      - SPOOF_PROTECTION=0
    cap_add:
      # - NET_ADMIN # For Fail2Ban to work
      - SYS_PTRACE
    extra_hosts:
      - "mailserver:192.168.0.00" #!TODO change
    restart: always
